# GitJobs chart default configuration values

imagePullSecrets: []
imageTag: ""
nameOverride: ""
pullPolicy: IfNotPresent

# Enable dynamic resource name prefix
#
# Enabling the dynamic resource name prefix ensures that the resources are named dynamically based on the Helm
# installation's name. This allows multiple installations of this chart in a single Kubernetes namespace. The prefix
# can be defined by using the `fullnameOverride`.
dynamicResourceNamePrefixEnabled: false

# Overwrites the installation's fullname generation (used for the dynamic resource name prefix)
fullnameOverride: ""

# Directory path where the configuration files should be mounted
configDir: "/home/gitjobs/.config/gitjobs"

# Database configuration
db:
  host: ""
  port: 5432
  dbname: gitjobs
  user: postgres
  password: postgres

# Email configuration
email:
  # From address used in emails
  fromAddress: ""
  # From name used in emails
  fromName: ""
  # SMTP server configuration
  smtp:
    # Hostname
    host: ""
    # Port
    port: 587
    # Username
    username: ""
    # Password
    password: ""

# Log configuration
log:
  # Output format [json|pretty]
  format: json

# Database migrator configuration
dbmigrator:
  job:
    image:
      # Database migrator image repository (without the tag)
      repository: gitjobs/dbmigrator

# Server configuration
server:
  # Address to listen on
  addr: 0.0.0.0:9000

  # Analytics configuration
  analytics:
    # Google Tag ID
    googleTagId: ""

    # Osano script URL
    osanoScriptUrl: ""

  # Base URL
  baseUrl: "https://{YOUR_GITJOBS_HOSTNAME}"

  # Basic auth configuration
  basicAuth:
    # Enable basic auth
    enabled: false
    # Basic auth username
    username: gitjobs
    # Basic auth password
    password: changeme

  # Cookie configuration
  cookie:
    secure: false

  # Login options enabled
  login:
    # Enable email login
    email: true
    # Enable GitHub login
    github: false
    # Enable Linux Foundation login
    linuxfoundation: false

  # OAuth2 configuration
  oauth2:
    # GitHub provider configuration
    github:
      # Auth URL
      authUrl: https://github.com/login/oauth/authorize
      # Client ID
      clientId: ""
      # Client secret
      clientSecret: ""
      # Redirect URI
      redirectUri: "https://{YOUR_GITJOBS_HOSTNAME}/log-in/oauth2/github/callback"
      # Scopes
      scopes:
        - "read:user"
        - "user:email"
      # Token URL
      tokenUrl: https://github.com/login/oauth/access_token

  # OIDC configuration
  oidc:
    # Linux Foundation SSO provider configuration
    linuxfoundation:
      # Client ID
      clientId: ""
      # Client secret
      clientSecret: ""
      # Issuer URL
      issuerUrl: https://{YOUR_OIDC_PROVIDER_ISSUER_URL}
      # Redirect URI
      redirectUri: "https://{YOUR_GITJOBS_HOSTNAME}/log-in/oidc/linuxfoundation/callback"
      # Scopes
      scopes:
        - openid
        - profile
        - email

  # Slack webhook URL to post new jobs published notifications
  slackWebhookUrl: ""

  # Ingress configuration
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    rules: []
    tls: []

  # Service configuration
  service:
    type: NodePort
    port: 80

  # Deployment configuration
  deploy:
    replicaCount: 1
    image:
      # Database migrator image repository (without the tag)
      repository: gitjobs/server
    resources: {}

# Syncer configuration
syncer:
  cronjob:
    image:
      # Syncer image repository (without the tag)
      repository: gitjobs/syncer
    resources: {}

# PostgreSQL configuration
postgresql:
  enabled: true
  auth:
    username: postgres
    password: postgres
    database: gitjobs
  image:
    repository: bitnami/postgresql
    tag: 17.2.0-debian-12-r3
  postgresqlDataDir: /data/pgdata
  primary:
    persistence:
      mountPath: /data
