name: End-to-end tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:17-3.5
        env:
          POSTGRES_USER: gitjobs
          POSTGRES_PASSWORD: password
          POSTGRES_DB: gitjobs
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust environment
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('''**/Cargo.lock''') }}

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Initialize npm and install dependencies
        run: |
          npm init -y
          npm install -D @playwright/test wait-on

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Standalone Tailwind CSS
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64
          chmod +x tailwindcss-linux-x64
          sudo mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss

      - name: Install tern
        run: |
          curl -sL https://github.com/jackc/tern/releases/download/v2.3.2/tern_2.3.2_linux_amd64.tar.gz -o tern.tar.gz
          tar -xzf tern.tar.gz
          sudo mv tern /usr/local/bin/

      - name: Build server
        run: cargo build --verbose --bin gitjobs-server

      - name: Prepare Database by Dropping Extensions
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: gitjobs
          PGPASSWORD: password
          PGDATABASE: gitjobs
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          psql -c "DROP EXTENSION IF EXISTS postgis CASCADE;"
          psql -c "DROP EXTENSION IF EXISTS pgcrypto CASCADE;"
          psql -c "DROP EXTENSION IF EXISTS pg_trgm CASCADE;"
      - name: Run database migrations
        working-directory: database/migrations
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: gitjobs
          PGPASSWORD: password
          PGDATABASE: gitjobs
          TERN_CONF: ${{ github.workspace }}/database/migrations/tern.conf
        run: |
          touch tern.conf
          bash ./migrate.sh
          sleep 5

      - name: Insert test data
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: gitjobs
          PGPASSWORD: password
          PGDATABASE: gitjobs
        run: |
          psql -c "INSERT INTO employer (employer_id, company, created_at, description, public) VALUES ('18fff2d7-c794-4130-85e4-76b9d7c60b72', 'Test Inc.', '2025-08-25 09:20:05.88454+02', 'test', false);"
          psql <<'EOF'
          INSERT INTO job (employer_id, title, description, kind, seniority, workplace, status, salary, salary_currency, salary_period, skills, published_at) VALUES
          ('18fff2d7-c794-4130-85e4-76b9d7c60b72', 'Frontend Developer', 'React expert', 'full-time', 'senior', 'remote', 'published', 120000, 'USD', 'year', '{"React", "TypeScript", "JavaScript"}', CURRENT_TIMESTAMP),
          ('18fff2d7-c794-4130-85e4-76b9d7c60b72', 'Backend Developer', 'Node.js expert', 'full-time', 'senior', 'hybrid', 'published', 130000, 'USD', 'year', '{"Node.js", "PostgreSQL", "REST"}', CURRENT_TIMESTAMP),
          ('18fff2d7-c794-4130-85e4-76b9d7c60b72', 'DevOps Engineer', 'Kubernetes expert', 'full-time', 'lead', 'on-site', 'published', 150000, 'USD', 'year', '{"Kubernetes", "Docker", "AWS"}', CURRENT_TIMESTAMP),
          ('18fff2d7-c794-4130-85e4-76b9d7c60b72', 'Data Scientist', 'Python expert', 'part-time', 'mid', 'remote', 'published', 80000, 'USD', 'year', '{"Python", "Pandas", "scikit-learn"}', CURRENT_TIMESTAMP),
          ('18fff2d7-c794-4130-85e4-76b9d7c60b72', 'UI/UX Designer', 'Figma expert', 'contractor', 'junior', 'remote', 'published', 60000, 'USD', 'year', '{"Figma", "UI", "UX"}', CURRENT_TIMESTAMP),
          ('18fff2d7-c794-4130-85e4-76b9d7c60b72', 'Software Engineer in Test', 'Playwright expert', 'full-time', 'mid', 'hybrid', 'published', 110000, 'USD', 'year', '{"Playwright", "TypeScript", "CI/CD"}', CURRENT_TIMESTAMP),
          ('18fff2d7-c794-4130-85e4-76b9d7c60b72', 'Product Manager', 'Agile expert', 'full-time', 'senior', 'on-site', 'published', 140000, 'USD', 'year', '{"Agile", "Scrum", "Jira"}', CURRENT_TIMESTAMP),
          ('18fff2d7-c794-4130-85e4-76b9d7c60b72', 'Mobile Developer', 'React Native expert', 'internship', 'entry', 'remote', 'published', 40000, 'USD', 'year', '{"React Native", "iOS", "Android"}', CURRENT_TIMESTAMP),
          ('18fff2d7-c794-4130-85e4-76b9d7c60b72', 'Full-stack Developer', 'Ruby on Rails expert', 'full-time', 'mid', 'hybrid', 'published', 115000, 'USD', 'year', '{"Ruby on Rails", "PostgreSQL", "React"}', CURRENT_TIMESTAMP),
          ('18fff2d7-c794-4130-85e4-76b9d7c60b72', 'Security Engineer', 'Cybersecurity expert', 'full-time', 'lead', 'on-site', 'published', 160000, 'USD', 'year', '{"Cybersecurity", "Penetration Testing", "CISSP"}', CURRENT_TIMESTAMP);
          EOF

      - name: Create Server Config File
        run: |
          cat <<EOF > config.testing.yml
          db:
            url: postgres://gitjobs:password@127.0.0.1:5432/gitjobs
          email:
            from_address: "test@example.com"
            from_name: "Test"
            smtp:
              host: "127.0.0.1"
              port: 2525
              username: "test"
              password: "password"
          log:
            format: "pretty"
          server:
            addr: "0.0.0.0:8080"
            base_url: "http://127.0.0.1:8080"
            login:
              email: true
              github: true
              linuxfoundation: false
            oauth2:
              github:
                auth_url: "https://github.com/login/oauth/authorize"
                client_id: "dummy_client_id"
                client_secret: "dummy_client_secret"
                redirect_uri: "http://127.0.0.1:8080/auth/github/callback"
                scopes: ["read:user", "user:email"]
                token_url: "https://github.com/login/oauth/access_token"
            oidc: {}
          EOF

      - name: Start server and wait for it to be ready
        uses: JarvusInnovations/background-action@v1
        with:
          run: ./target/debug/gitjobs-server --config-file config.testing.yml > server.log 2>&1 &
          wait-on: http://localhost:8080

      - name: Run Playwright tests
        run: npx playwright test --config tests/e2e/playwright.config.ts
        env:
          BASE_URL: http://127.0.0.1:8080
